import { Injectable } from '@angular/core';
import { Ticket } from './ticket.model';
import { Subject } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class TicketsService {
  private tickets: Ticket [] = [];
  private ticketsUpdated = new Subject<Ticket[]>();

  constructor(private http: HttpClient, private router: Router) { }

  addTicket(inputTicket: Ticket){
    const newTicket: Ticket = inputTicket;
    this.http.post<{message: string, ticketId: string}>('http://localhost:3000/api/tickets', newTicket)
    .subscribe(
      (responseData) => {
        //update id with the one generated by mongo
        const generatedTicketId = responseData.ticketId;
        newTicket.id = generatedTicketId;
        this.tickets.push(newTicket);
        this.ticketsUpdated.next([...this.tickets]);
        console.log(this.tickets);
        //push only on success
        this.router.navigate(['/tickets']);
      }
    );
  }



  updateTicket(ads: any){

  }

  getTicket(asda: any){

  }
}
